### PR TITLE
Fix typo

### PR DESCRIPTION
**Pull request by dawei-wang**
Fix xparq/sfw2#211

### CODE REVIEW

**Comment by xparq** [comment]
WTF is this bogus pull request, out of the blue?! :-o

**Comment by xparq** [comment]
Wow, now I see it's still not corrected! :-o Thanks!!! 
I thought this PR was some other bogus case of GitHub misidentifying the owner of some activities...

**Comment by dawei-wang** [comment]
Hi @xparq I have bookmarked a search for open issues containing the word typo on github. I primarily work at mdn as a freelance technical writer and love to help out open-source. I am a real human being. I also do this to build up my resume as an aspiring front end developer and accessibility specialist in the future.

**Comment by xparq** [comment]
Cool! :)

**Pull request merged**
